-- AlterTable
ALTER TABLE `ApiKey` MODIFY `kind` ENUM('GEMINI', 'TWELVE_DATA', 'CRYPTOPANIC', 'ETHERSCAN', 'BSCSCAN', 'COINGECKO', 'BITGET', 'BINANCE', 'MEXC', 'OKX', 'METAAPI', 'TELEGRAM', 'CUSTOM') NOT NULL;
