-- CreateTable
CREATE TABLE `BrokerOrder` (
    `id` VARCHAR(191) NOT NULL,
    `userId` VARCHAR(191) NOT NULL,
    `tradeJournalId` VARCHAR(191) NOT NULL,
    `broker` VARCHAR(191) NOT NULL,
    `clientOid` VARCHAR(191) NOT NULL,
    `attempt` INTEGER NOT NULL DEFAULT 1,
    `externalOrderId` VARCHAR(191) NULL,
    `status` ENUM('PENDING', 'PLACED', 'PLACED_NO_SL', 'FAILED', 'CANCELLED', 'UNKNOWN') NOT NULL DEFAULT 'PENDING',
    `symbol` VARCHAR(191) NOT NULL,
    `side` VARCHAR(191) NOT NULL,
    `orderType` VARCHAR(191) NOT NULL,
    `productType` VARCHAR(191) NOT NULL,
    `marginCoin` VARCHAR(191) NOT NULL,
    `marginMode` VARCHAR(191) NOT NULL,
    `posMode` VARCHAR(191) NOT NULL,
    `leverage` INTEGER NOT NULL,
    `size` VARCHAR(191) NOT NULL,
    `price` VARCHAR(191) NULL,
    `presetStopLoss` VARCHAR(191) NULL,
    `presetTakeProfit` VARCHAR(191) NULL,
    `requestedSize` DECIMAL(20, 8) NULL,
    `requestedPrice` DECIMAL(20, 8) NULL,
    `sentBody` JSON NULL,
    `rawResponse` JSON NULL,
    `errorStage` VARCHAR(191) NULL,
    `errorCode` VARCHAR(191) NULL,
    `errorMessage` TEXT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    INDEX `BrokerOrder_userId_createdAt_idx`(`userId`, `createdAt`),
    INDEX `BrokerOrder_tradeJournalId_idx`(`tradeJournalId`),
    INDEX `BrokerOrder_status_idx`(`status`),
    UNIQUE INDEX `BrokerOrder_broker_clientOid_key`(`broker`, `clientOid`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
